#![no_std]

pub mod force_data_packet;
pub const FORCE_SENS_BAUD: u32 = 115_200;

pub use force_data_packet::{
    FORCE_DATA_PACKET_LEN, FORCE_MAX_READING, FORCE_SENSOR_COUNT, FORCE_SENSOR_INDEX_IDX,
    FORCE_SENSOR_MIDDLE_IDX, FORCE_SENSOR_PALM_1_IDX, FORCE_SENSOR_PALM_2_IDX, FORCE_SENSOR_PALM_3_IDX,
    FORCE_SENSOR_PALM_4_IDX, FORCE_SENSOR_PALM_5_IDX, FORCE_SENSOR_PINKY_IDX, FORCE_SENSOR_RING_IDX,
    FORCE_SENSOR_THUMB_IDX, ForceDataPacket, ForceDataPacketError, encode_readings_unchecked,
};
